---
title: "How to prepare data for statistical analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how-to-prepare-data-for-statistical-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, warning=FALSE, message=FALSE}
# library(goodpracticestools)
library(dplyr)
library(stringr)
library(knitr)
pkgload::load_all()
```

## Raw data

The raw FR example data is available in the `"data_raw_fr"` dataset:

```{r}
data("data_raw_fr")
head(data_raw_fr) |> 
  mutate(
    across(
      everything(), 
      ~ str_trunc(.x, 20)
    )
  ) |> 
  kable()
```

The DE version is available in the `"data_raw_de"` dataset:

```{r}
data("data_raw_de")
head(data_raw_de) |> 
  mutate(
    across(
      everything(), 
      ~ str_trunc(.x, 20)
    )
  ) |> 
  kable()
```

## How to prepare data for statistical analysis

Only French data are used for the stat aanalysis
To avoid deisconeande entre jeux de données

- Check that the expected columns are present

```{r}
data_fr <- prepare_data(
  data = data_raw_fr
)
```

