---
title: "Architecture Decision Records"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{adr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## ADR002: Management of external model dependencies in CI

#### Background

Contrary to the initial intention, we cannot have the full CI process because, in the vignettes of the package and unit tests, we call the NLP model **SpaCy** (Python) and the LLM **Ollama**. While this works well locally, it requires additional configuration to work properly in the CI (GitHub workflow).

#### Decision

A code coverage report and vignettes are generated locally and included in the `pkgdown` site before each push to the `main` branch of the GitHub repository. The `pkgdown` site is then deployed based on this local build. 

Unit tests that involve Python models are marked with `skip_on_ci()`, and vignettes are not built during `devtools::check()` in the CI. However, everything is run and verified locally before pushing to the GitHub repo.

Instructions for this process are included in the file `dev/check_and_config_before_merge.R`. 

#### Risks

- There is a risk of manual build steps being forgotten before pushing

- By not running these tests in the CI, potential compatibility issues for some operating systems (notably Windows and Linux) may go undetected, as development is locally done on macOS

## ADR001: Management of two languages (FR and DE) in data analysis

#### Background

The HTML overview must be available in two languages (French and German) because the recipients in the Swiss cantons speak one of these two languages.

The data on the projects (in XLSX format) is available in both French and German, with the extraction having been done from the PSCH organization's data software.

The question arises of how to manage both files in parallel during data analysis, especially since marginal differences —though still differences— were observed in the raw data.

*Note: The existence of differences was identified by performing Factor Analysis on each of the raw datasets. The eigenvalues from these two analyses were not strictly identical, indicating differences in the raw data.*

#### Decision

The analyses (graphs, factor analyses, classification, interpretation of classes) will be carried out using **only the French raw dataset**. These will **then be translated into German**, as the translations required are expected to be marginal. However, the raw tables displayed in the summary will show the French raw data on one side and the German raw data on the other, in order to avoid the complexity of translation at this stage.

#### Risks

- There may be poor translation in German for statistical analyses

- The German results may not align perfectly with the DE raw data
