#' data_fr
#'
#' Toy prepared French data about projects.
#'
#' @format A data frame with 170 rows and 282 variables:
#' \describe{
#'   \item{ fiche_d_informations_id }{  character }
#'   \item{ nom }{  character }
#'   \item{ niveau }{  character }
#'   \item{ i_enfants_adolescents }{  character }
#'   \item{ ii_adultes }{  character }
#'   \item{ iii_personnes_agees }{  character }
#'   \item{ a_enfants_adolescents_nutrition_activite_physique }{  character }
#'   \item{ b_personnes_agees_nutrition_activite_physique }{  character }
#'   \item{ c_enfants_adolescents_sante_psychique }{  character }
#'   \item{ d_personnes_agees_sante_psychique }{  character }
#'   \item{ theme_activite_physique }{  character }
#'   \item{ theme_alimentation }{  character }
#'   \item{ theme_sante_psychique }{  character }
#'   \item{ theme_autres_themes_kommunale_gesundheitsforderung_pravention }{  character }
#'   \item{ theme_autres_themes_ch_gesundheitsforderung_von_gruppen }{  character }
#'   \item{ theme_autres_themes }{  character }
#'   \item{ theme_autres_themes_allg_kommunale_gesundheitsforderung_pravention }{  character }
#'   \item{ theme_autres_themes_ch_gesundheitsforderung_in_gruppen }{  character }
#'   \item{ groupe_cible_non_applicable }{  character }
#'   \item{ groupe_cible_ensemble_de_la_population }{  character }
#'   \item{ groupe_cible_les_multiplicateur_trice_s_sont_le_groupe_cible_primaire_de_cette_mesure }{  character }
#'   \item{ groupe_cible_troisieme_age_en_sante }{  character }
#'   \item{ groupe_cible_premieres_limitations_aux_troisieme_quatrieme_ages }{  character }
#'   \item{ groupe_cible_dependance_fonctionnelle_au_quatrieme_age }{  character }
#'   \item{ groupe_cible_adolescent_e_s_et_jeunes_adultes }{  character }
#'   \item{ groupe_cible_enfants_d_age_scolaire }{  character }
#'   \item{ groupe_cible_enfants_d_age_scolaire_moyen }{  character }
#'   \item{ groupe_cible_enfants_d_age_scolaire_superieur_debut_adolescence }{  character }
#'   \item{ groupe_cible_enfants_en_bas_age_d_age_prescolaire }{  character }
#'   \item{ groupe_cible_adolescent_e_s }{  character }
#'   \item{ groupe_cible_grossesse }{  character }
#'   \item{ groupe_cible_nourrissons }{  character }
#'   \item{ setting_autres_settings_samtliche_themen_rund_um_das_alter }{  character }
#'   \item{ setting_commune_quartier_environnement_residentiel }{  character }
#'   \item{ setting_installation_de_loisirs_association }{  character }
#'   \item{ setting_famille_domicile }{  character }
#'   \item{ setting_lieux_d_accueil_et_d_education_extra_familiaux }{  character }
#'   \item{ setting_ecole_de_l_ecole_enfantine_au_niveau_tertiaire }{  character }
#'   \item{ setting_pas_de_setting_specifique }{  character }
#'   \item{ setting_autres_settings_gemeindeverwaltung }{  character }
#'   \item{ setting_autres_settings_pro_senectute_beratungsstelle }{  character }
#'   \item{ setting_autres_settings_internet }{  character }
#'   \item{ setting_autres_settings_ecole_cycle_1et_2 }{  character }
#'   \item{ setting_autres_settings_entreprise_dapprentissage }{  character }
#'   \item{ setting_autres_settings_breite_offentlichkeit }{  character }
#'   \item{ setting_autres_settings }{  character }
#'   \item{ setting_autres_settings_setting_ubergreifend }{  character }
#'   \item{ setting_autres_settings_offentliche_raume }{  character }
#'   \item{ setting_alterswohnungen_und_siedlungen }{  character }
#'   \item{ setting_autres_settings_vor_der_einschulung }{  character }
#'   \item{ setting_autres_settings_autres_settings }{  character }
#'   \item{ desc_● }{  numeric }
#'   \item{ desc_accompagnement }{  numeric }
#'   \item{ desc_accompagner }{  numeric }
#'   \item{ desc_acteur }{  numeric }
#'   \item{ desc_action }{  numeric }
#'   \item{ desc_activité }{  numeric }
#'   \item{ desc_adapter }{  numeric }
#'   \item{ desc_adolescent }{  numeric }
#'   \item{ desc_adresse }{  numeric }
#'   \item{ desc_adulte }{  numeric }
#'   \item{ desc_afin }{  numeric }
#'   \item{ desc_âge }{  numeric }
#'   \item{ desc_âgé }{  numeric }
#'   \item{ desc_agir }{  numeric }
#'   \item{ desc_aide }{  numeric }
#'   \item{ desc_aider }{  numeric }
#'   \item{ desc_ainsi }{  numeric }
#'   \item{ desc_alimentation }{  numeric }
#'   \item{ desc_améliorer }{  numeric }
#'   \item{ desc_an }{  numeric }
#'   \item{ desc_année }{  numeric }
#'   \item{ desc_apprendre }{  numeric }
#'   \item{ desc_apprennent }{  numeric }
#'   \item{ desc_apprenti }{  numeric }
#'   \item{ desc_apprentissage }{  numeric }
#'   \item{ desc_approche }{  numeric }
#'   \item{ desc_après }{  numeric }
#'   \item{ desc_association }{  numeric }
#'   \item{ desc_atelier }{  numeric }
#'   \item{ desc_atteindre }{  numeric }
#'   \item{ desc_aussi }{  numeric }
#'   \item{ desc_autre }{  numeric }
#'   \item{ desc_base }{  numeric }
#'   \item{ desc_baser }{  numeric }
#'   \item{ desc_besoin }{  numeric }
#'   \item{ desc_bien }{  numeric }
#'   \item{ desc_bon }{  numeric }
#'   \item{ desc_bouge }{  numeric }
#'   \item{ desc_cadre }{  numeric }
#'   \item{ desc_canton }{  numeric }
#'   \item{ desc_cantonal }{  numeric }
#'   \item{ desc_centre }{  numeric }
#'   \item{ desc_ch }{  numeric }
#'   \item{ desc_chez }{  numeric }
#'   \item{ desc_classe }{  numeric }
#'   \item{ desc_collaboration }{  numeric }
#'   \item{ desc_comme }{  numeric }
#'   \item{ desc_comment }{  numeric }
#'   \item{ desc_commun }{  numeric }
#'   \item{ desc_commune }{  numeric }
#'   \item{ desc_compétence }{  numeric }
#'   \item{ desc_comportement }{  numeric }
#'   \item{ desc_comprendre }{  numeric }
#'   \item{ desc_concept }{  numeric }
#'   \item{ desc_concerner }{  numeric }
#'   \item{ desc_condition }{  numeric }
#'   \item{ desc_confiance }{  numeric }
#'   \item{ desc_conflit }{  numeric }
#'   \item{ desc_connaissance }{  numeric }
#'   \item{ desc_conseil }{  numeric }
#'   \item{ desc_contribuer }{  numeric }
#'   \item{ desc_corps }{  numeric }
#'   \item{ desc_cours }{  numeric }
#'   \item{ desc_crèche }{  numeric }
#'   \item{ desc_créer }{  numeric }
#'   \item{ desc_deux }{  numeric }
#'   \item{ desc_développement }{  numeric }
#'   \item{ desc_développer }{  numeric }
#'   \item{ desc_devoir }{  numeric }
#'   \item{ desc_différent }{  numeric }
#'   \item{ desc_direction }{  numeric }
#'   \item{ desc_domaine }{  numeric }
#'   \item{ desc_durable }{  numeric }
#'   \item{ desc_e }{  numeric }
#'   \item{ desc_échange }{  numeric }
#'   \item{ desc_échanger }{  numeric }
#'   \item{ desc_école }{  numeric }
#'   \item{ desc_éducation }{  numeric }
#'   \item{ desc_également }{  numeric }
#'   \item{ desc_élève }{  numeric }
#'   \item{ desc_encourager }{  numeric }
#'   \item{ desc_enfance }{  numeric }
#'   \item{ desc_enfant }{  numeric }
#'   \item{ desc_enseignement }{  numeric }
#'   \item{ desc_enseigner }{  numeric }
#'   \item{ desc_ensembl }{  numeric }
#'   \item{ desc_ensemble }{  numeric }
#'   \item{ desc_entraider }{  numeric }
#'   \item{ desc_entrer }{  numeric }
#'   \item{ desc_environnement }{  numeric }
#'   \item{ desc_équilibré }{  numeric }
#'   \item{ desc_espace }{  numeric }
#'   \item{ desc_estime }{  numeric }
#'   \item{ desc_etc }{  numeric }
#'   \item{ desc_être }{  numeric }
#'   \item{ desc_événement }{  numeric }
#'   \item{ desc_exemple }{  numeric }
#'   \item{ desc_exercice }{  numeric }
#'   \item{ desc_expérience }{  numeric }
#'   \item{ desc_faire }{  numeric }
#'   \item{ desc_famille }{  numeric }
#'   \item{ desc_favoriser }{  numeric }
#'   \item{ desc_femme }{  numeric }
#'   \item{ desc_fois }{  numeric }
#'   \item{ desc_formation }{  numeric }
#'   \item{ desc_forme }{  numeric }
#'   \item{ desc_forum }{  numeric }
#'   \item{ desc_gestion }{  numeric }
#'   \item{ desc_grâce }{  numeric }
#'   \item{ desc_grand }{  numeric }
#'   \item{ desc_groupe }{  numeric }
#'   \item{ desc_heure }{  numeric }
#'   \item{ desc_idée }{  numeric }
#'   \item{ desc_important }{  numeric }
#'   \item{ desc_information }{  numeric }
#'   \item{ desc_institution }{  numeric }
#'   \item{ desc_jeu }{  numeric }
#'   \item{ desc_jeune }{  numeric }
#'   \item{ desc_là }{  numeric }
#'   \item{ desc_langue }{  numeric }
#'   \item{ desc_lier }{  numeric }
#'   \item{ desc_lieu }{  numeric }
#'   \item{ desc_ligne }{  numeric }
#'   \item{ desc_local }{  numeric }
#'   \item{ desc_lors }{  numeric }
#'   \item{ desc_ludique }{  numeric }
#'   \item{ desc_lui }{  numeric }
#'   \item{ desc_maladie }{  numeric }
#'   \item{ desc_manière }{  numeric }
#'   \item{ desc_matériel }{  numeric }
#'   \item{ desc_matière }{  numeric }
#'   \item{ desc_même }{  numeric }
#'   \item{ desc_mesure }{  numeric }
#'   \item{ desc_mettre }{  numeric }
#'   \item{ desc_mise }{  numeric }
#'   \item{ desc_mobilité }{  numeric }
#'   \item{ desc_national }{  numeric }
#'   \item{ desc_niveau }{  numeric }
#'   \item{ desc_nombreux }{  numeric }
#'   \item{ desc_non }{  numeric }
#'   \item{ desc_nouveau }{  numeric }
#'   \item{ desc_objectif }{  numeric }
#'   \item{ desc_œuvre }{  numeric }
#'   \item{ desc_offre }{  numeric }
#'   \item{ desc_offrir }{  numeric }
#'   \item{ desc_organisation }{  numeric }
#'   \item{ desc_organiser }{  numeric }
#'   \item{ desc_outil }{  numeric }
#'   \item{ desc_p }{  numeric }
#'   \item{ desc_parent }{  numeric }
#'   \item{ desc_participant }{  numeric }
#'   \item{ desc_pendant }{  numeric }
#'   \item{ desc_permettre }{  numeric }
#'   \item{ desc_personne }{  numeric }
#'   \item{ desc_personnel }{  numeric }
#'   \item{ desc_petit }{  numeric }
#'   \item{ desc_physique }{  numeric }
#'   \item{ desc_place }{  numeric }
#'   \item{ desc_plan }{  numeric }
#'   \item{ desc_plateform }{  numeric }
#'   \item{ desc_plus }{  numeric }
#'   \item{ desc_point }{  numeric }
#'   \item{ desc_politique }{  numeric }
#'   \item{ desc_population }{  numeric }
#'   \item{ desc_positif }{  numeric }
#'   \item{ desc_possibilité }{  numeric }
#'   \item{ desc_possible }{  numeric }
#'   \item{ desc_pouvoir }{  numeric }
#'   \item{ desc_pratique }{  numeric }
#'   \item{ desc_précoce }{  numeric }
#'   \item{ desc_premier }{  numeric }
#'   \item{ desc_prendre }{  numeric }
#'   \item{ desc_prévention }{  numeric }
#'   \item{ desc_primaire }{  numeric }
#'   \item{ desc_prise }{  numeric }
#'   \item{ desc_pro }{  numeric }
#'   \item{ desc_problème }{  numeric }
#'   \item{ desc_proche }{  numeric }
#'   \item{ desc_professionnel }{  numeric }
#'   \item{ desc_programme }{  numeric }
#'   \item{ desc_projet }{  numeric }
#'   \item{ desc_promotion }{  numeric }
#'   \item{ desc_promouvoir }{  numeric }
#'   \item{ desc_proposer }{  numeric }
#'   \item{ desc_propre }{  numeric }
#'   \item{ desc_psychique }{  numeric }
#'   \item{ desc_public }{  numeric }
#'   \item{ desc_qualité }{  numeric }
#'   \item{ desc_quartier }{  numeric }
#'   \item{ desc_question }{  numeric }
#'   \item{ desc_quotidien }{  numeric }
#'   \item{ desc_recevoir }{  numeric }
#'   \item{ desc_réduire }{  numeric }
#'   \item{ desc_relation }{  numeric }
#'   \item{ desc_rencontre }{  numeric }
#'   \item{ desc_renforcer }{  numeric }
#'   \item{ desc_réseau }{  numeric }
#'   \item{ desc_responsable }{  numeric }
#'   \item{ desc_ressource }{  numeric }
#'   \item{ desc_rôle }{  numeric }
#'   \item{ desc_sain }{  numeric }
#'   \item{ desc_santé }{  numeric }
#'   \item{ desc_scolaire }{  numeric }
#'   \item{ desc_semaine }{  numeric }
#'   \item{ desc_sensibilisation }{  numeric }
#'   \item{ desc_service }{  numeric }
#'   \item{ desc_site }{  numeric }
#'   \item{ desc_situation }{  numeric }
#'   \item{ desc_social }{  numeric }
#'   \item{ desc_société }{  numeric }
#'   \item{ desc_sou }{  numeric }
#'   \item{ desc_soutenir }{  numeric }
#'   \item{ desc_soutien }{  numeric }
#'   \item{ desc_sport }{  numeric }
#'   \item{ desc_suisse }{  numeric }
#'   \item{ desc_suivre }{  numeric }
#'   \item{ desc_sujet }{  numeric }
#'   \item{ desc_tel }{  numeric }
#'   \item{ desc_temps }{  numeric }
#'   \item{ desc_thématique }{  numeric }
#'   \item{ desc_thème }{  numeric }
#'   \item{ desc_tout }{  numeric }
#'   \item{ desc_travail }{  numeric }
#'   \item{ desc_trois }{  numeric }
#'   \item{ desc_vie }{  numeric }
#'   \item{ desc_vieilless }{  numeric }
#'   \item{ desc_vise }{  numeric }
#'   \item{ desc_viser }{  numeric }
#'   \item{ desc_vivre }{  numeric }
#'   \item{ desc_www }{  numeric }
#'   \item{ desc_youp }{  numeric }
#' }
#' @source Source
"data_fr"
