name: R-CMD-check.yaml

permissions: read-all

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      # Install spaCy and spaCyR for macOS
      - name: Install spaCy and spaCyR (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install python
          pip3 install spacy
          python3 -m spacy download fr_core_news_sm
          Rscript -e "install.packages('spacyr')"
          Rscript -e "library(spacyr); spacy_install()"

      # Install spaCy and spaCyR for Windows
      - name: Install spaCy and spaCyR (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install python
          pip install spacy
          python -m spacy download fr_core_news_sm
          Rscript -e "install.packages('spacyr')"
          Rscript -e "library(spacyr); spacy_install()"

      # Install spaCy and spaCyR for Ubuntu
      - name: Install spaCy and spaCyR (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install python3-pip python3-dev
          pip3 install spacy
          python3 -m spacy download fr_core_news_sm
          Rscript -e "install.packages('spacyr')"
          Rscript -e "library(spacyr); spacy_install()"

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
